/// Flutter icons RupeeIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RupeeIcon
///      fonts:
///       - asset: fonts/RupeeIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class RupeeIcon {
  RupeeIcon._();

  static const _kFontFam = 'RupeeIcon';

  static const IconData rupee_icon = const IconData(0xe800, fontFamily: _kFontFam);
}
